spring.application.name=tp
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/receipt_scanner_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:IMAr2005}
spring.jpa.hibernate.ddl-auto=update